name = "phantomsecondline"
main="src/index.ts"
compatibility_date = "2024-11-06"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "phantomsecondline"
database_id = "c863cc1b-dc9a-401c-82ee-c040241b1e67"
preview_database_id = "test"
migrations_dir = "migrations"

[observability]
enabled = true
